version: '3.9'

services:
  db:
    image: mysql:8.4
    container_name: ganie-tryout-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ganie-tryout
      MYSQL_USER: ganie-tryout
      MYSQL_PASSWORD: ganie-tryout
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

volumes:
  mysql-data: