version: '3.9'

services:
  db:
    image: postgres:16
    container_name: ganie-tryout-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ganie-tryout
      POSTGRES_PASSWORD: ganie-tryout
      POSTGRES_DB: ganie-tryout
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: